services:
  database:
    image: postgres:16-alpine
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
volumes:
  database-data: {}
